# project Information
site_name: Ismail's Website
site_description: 'A project documentation website'
site_author: 'Ismail Mansuri'
site_url: 'http://www.ismailmansuri.com'
site_dir: 'D:\Ismail\Documents\website\html'

# Repository
repo_name: 
repo_url: https://github.com/IsmailMansuri
edit_uri: ''

# Copyright
copyright: 'Copyright &copy; 2017 - 2023 Ismail Mansuri'

# Page Tree
nav:
  - Home: index.md
  - Projects:
    - Go Kart: Projects/gokart.md
    - Trailer: Projects/trailer.md
    - CNC: Projects/cnc.md
    - My Website: Projects/website.md
  - Activities:
    - SAE Baja: Activities/baja.md
    - 4H Robotics Club: Activities/4h.md
    - FIRST Team 12601: Activities/12601.md
    - Game-U: Activities/gameu.md

# Configuration
theme:
  name: material
  custom_dir: overrides
  language: en
  palette:
    scheme: slate
    primary: light blue
    accent: green
  icon:
    logo: 'material/send-outline'
  favicon: 'img/favicon.png'
  features:
    - navigation.instant

# Extras
extra:
  social:
    - icon: 'material/email'
      link: 'mailto:info@ismailmansuri.com'
    - icon: 'material/phone'
      link: 'tel:9083490496'
    - icon: 'material/github'
      link: 'https://github.com/IsmailMansuri'
    - icon: 'material/linkedin'
      link: 'https://www.linkedin.com/in/IsmailMansuri'

# Google Analytics
google_analytics:
  - 'UA-129524041-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - meta

plugins:
  - search